### ISSUE TITLE
Quadratic compile times with AllZip constraints

### ISSUE THREAD

**Issue by hsenag** [well-typed/generics-sop#105]
The cut down code below takes approximately 6s to compile on my machine (including Windows and cabal overhead) without `-DBIGGER`, and 18s with `-DBIGGER`. Adding another row of Ints takes that to 40s. If the `AllZipF` constraint is removed from `dumpFields` then it takes ~6s regardless of how many Ints there are.

```
{-# LANGUAGE CPP #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeFamilies #-}
module Code
  ( dumpRow
  ) where

import Generics.SOP
import Generics.SOP.Constraint

type CodeRecord =
      '[
         Int, Int, Int, Int, Int, Int, Int, Int, Int, Int
#ifdef BIGGER
       , Int, Int, Int, Int, Int, Int, Int, Int, Int, Int
       , Int, Int, Int, Int, Int, Int, Int, Int, Int, Int
       , Int, Int, Int, Int, Int, Int, Int, Int, Int, Int
#endif
      ]

dumpRow :: NS I CodeRecord -> [String]
dumpRow = dumpFields

dumpFields :: (AllZipF (~) as as) => NS I as -> [String]
dumpFields = const []

```

I tracked it down to the definition of AllZipF:

```type family
  AllZipF (c :: a -> b -> Constraint) (xs :: [a]) (ys :: [b])
    :: Constraint where
  AllZipF _c '[]      '[]        = ()
  AllZipF  c (x ': xs) (y ': ys) = (c x y, AllZip c xs ys)

class
  ( SListI xs, SListI ys
  , SameShapeAs xs ys, SameShapeAs ys xs
  , AllZipF c xs ys
  ) => AllZip (c :: a -> b -> Constraint) (xs :: [a]) (ys :: [b])
instance
  ( SListI xs, SListI ys
  , SameShapeAs xs ys, SameShapeAs ys xs
  , AllZipF c xs ys
  ) => AllZip c xs ys
```

I think the recursive dependency to `AllZip` means that the `SameShape` constraints have to be solved again and again.

I tried changing the recursive case to depend on `AllZipF` directly:

```  AllZipF  c (x ': xs) (y ': ys) = (c x y, AllZipF c xs ys)```

Both `sop-core` and `generics-sop` compile fine, and the `generics-sop` tests pass. The slowdown in the code above is gone. (My real application also subjectively seems a lot better, but I think there may be another performance problem to track down after this one.)

Intuitively it seems like the same fix might be needed in `AllF`, but that causes a compile failure in `sop-core`.

I'm not sure if there are any other possible gotchas with the code change, particularly as it'll break the symmetry with `AllF`. I'll send in a pull request anyway, but thought a separate issue would be the best way to document the problem it's fixing.

**Comment by kosmikus** [comment]
You're showing your fixed version already, right? I guess the original is
```
AllZipF (c :: a -> b -> Constraint) (xs :: [a]) (ys :: [b])
    :: Constraint where
  AllZipF _c '[]      '[]        = ()
  AllZipF  c (x ': xs) (y ': ys) = (c x y, AllZip c xs ys)
```

Unfortunately, I think this changes semantics, which is also the reason why doing the same change for `AllF` fails. This is related to the discussion in #98. I'll have to make some experiments.

**Comment by hsenag** [comment]
> You're showing your fixed version already, right?

Sorry, yes. Copy and paste failure while editing - I've updated the body now.

**Comment by kosmikus** [comment]
I think the real culprit is `SameShapeAs` which is another recursive type family that traverses the entire list and is called twice at each level. I furthermore think that for the primary purpose I introduced this, which was to help with type inference, I don't need it to be recursive. A shallow reveal that if one of the lists is a cons, the other must be as well, should be enough in conjunction with `AllZip` and `AllZipF`. Unfortunately, I cannot currently find the original code where I used it (it wasn't in production code, just in some experimental development).

But in any case, my current preference would be to change `SameShapeAs` to the following definition:
```
type family
  SameShapeAs (xs :: [a]) (ys :: [b]) :: Constraint where
  SameShapeAs '[]       ys = (ys ~ '[])
  SameShapeAs (x ': xs) ys = (ys ~ (Head ys ': Tail ys))
```

With this, your example compiles quickly enough. Perhaps you could check whether it also fixes the problem in your actual code without introducing new ones?

The potential fix is available in this branch: https://github.com/well-typed/generics-sop/tree/wip/issue-105

**Comment by hsenag** [comment]
> With this, your example compiles quickly enough. Perhaps you could check whether it also fixes the problem in your actual code without introducing new ones?

Yes, it seems to produce a similar performance improvement to the AllZipF change, and the code continues to build and work fine otherwise. Thanks!

(BTW the comment in the code says the slowdown is exponential, but I think it's "just" quadratic :-) )

**Comment by kosmikus** [comment]
Thanks. Yes, I think you're right about it being quadratic. I'll adapt the comment. How urgently do you need a new release? Strictly speaking, this would still require a major version bump, because it completely changes the behaviour of `SameShapeAs` which is exported and might in theory be used by people for other purposes. And if I'm forced to do a major version bump anyway, I'm tempted to look at #87 again. But that means there's always a risk it won't happen :)

**Comment by hsenag** [comment]
I can live with building against it locally for a while - cabal.project.local makes it fairly easy.

I'm also still seeing a bit of slowness in compilation of my real code (though much less than before) so I might dig into that a bit more now this effect isn't dominating to see if there's anything else coming from generics-sop or it's just my own type-level games causing trouble.

**Comment by kosmikus** [comment]
I've merged this fix into `master`. Closing for now.

**Comment by kosmikus** [comment]
@hsenag 0.5 is released now.

**Comment by hsenag** [comment]
Thanks!
