### ISSUE TITLE
Allow non-TH building?

### ISSUE THREAD

**Issue by adamConnerSax** [well-typed/generics-sop#61]
Is TH used only for Generic and HasDatatypeInfo instances?  If so, would it be possible to have a flag that allows generics-sop to compile without TH by skipping all the instance generation?  I'm trying to use generics-sop to add some functionality to a library that needs to have the option of no TH (for deployment on mobile). The core use just relies on the NS and NP types and doesn't require any instances.  Some other features would be unavailable without instances but that could be handled.

**Comment by kosmikus** [comment]
It's not really considered good style to have conditional interfaces depending on flags (because from other packages, you cannot specify that you need a package with a particular combination of flags). So the proper way to support your use case would be to split the package into a TH-free core package and to provide the TH support on top of that.

I'm willing to consider that, but it'd be a bit of reorganisation work, so I don't know how soon I will get around to it.

**Comment by phadej** [comment]
@kosmikus 
- we could use [`TemplateHaskellQuotes`](https://ghc.haskell.org/trac/ghc/ticket/11121), on GHC-8.0+
- dump splices for `Instances` module

Then we could compile `generics-sop` with non-TH GHC.

**Comment by adamConnerSax** [comment]
Thanks for considering how to do this!  I'd be happy to help if someone can tell me what to do.  
I think having the non-TH compile work only on 8.0+ would be fine for my needs but I am working to confirm that now.

**Comment by kosmikus** [comment]
@phadej Is this really better than splitting the package?

**Comment by phadej** [comment]
@kosmikus I guess one can get far without `.Instances`, but at some point you'll need them as well.

**Comment by kosmikus** [comment]
Solved via #75.
