### ISSUE TITLE
Documentation bug: hcollapse for NS

### ISSUE THREAD

**Issue by feuerbach** [well-typed/generics-sop#9]
From the docs:

``` haskell
hcollapse, collapse_NS  :: NS  (K a) xs  ->   a
```

But:

``` haskell
instance HCollapse NS  where hcollapse = I . collapse_NS
```

so in reality the types of `hcollapse` and `collapse_NS` differ by `I`.

Not submitting a pull request since this creates an ugly non-uniformity in the docs and I don't know how you prefer to resolve it. Perhaps change the type of `collapse_NS` to return an `I`? I don't know if anyone actually use the specialized versions.

**Comment by kosmikus** [comment]
Good catch! I think it should be made uniform, yes.

But which way? Make `collapse_NS` return an `I`, or change `hcollapse` to return a plain `a`. The latter would involve changing the definition of the `CollapseTo` type family, but that's probably ok.

Any preference?

**Comment by feuerbach** [comment]
I'd prefer not to have an `I`, of course. Also, I just realized that the POP instantiation has the same issue.

> The latter would involve changing the definition of the CollapseTo type family, but that's probably ok.

Right, you could eta-expand it, I suppose.

**Comment by kosmikus** [comment]
Ok, I've made the change to `CollapseTo` and `hcollapse`. This is an interface change, but I think it only simplifies things. I'm holding off a new release for a few days because I want to check if there are any similar issues in other functions that should be treated in the same way, and because I have to update the packages that depend on `generics-sop` and write a proper changelog.

**Comment by kosmikus** [comment]
This is done and will be in 0.2.
