### ISSUE TITLE
Hackage Haddocks give incorrect signatures

### ISSUE THREAD

**Issue by ttuegel** [well-typed/generics-sop#92]
The Hackage Haddocks for `generics-sop` give the wrong signature for the [constructors of `NS`](https://hackage.haskell.org/package/generics-sop-0.4.0.1/docs/Generics-SOP.html#t:NS), `NP`, and possibly others. For `NS`, it shows:
![screenshot_20181221_112650](https://user-images.githubusercontent.com/563054/50355205-7f505780-0513-11e9-8705-b3d8bd186e9b.png)
The kind signatures of these types are also incorrect.
The signatures are [shown correctly](https://hackage.haskell.org/package/sop-core-0.4.0.0/docs/Data-SOP-NS.html#t:NS) in the documentation of `sop-core`:
![screenshot_20181221_112701](https://user-images.githubusercontent.com/563054/50355265-b9215e00-0513-11e9-853e-c9099c5eef29.png)

**Comment by phadej** [comment]
I deleted the documentation. I was build with GHC-8.4.3; not it should be rebuild with GHC-8.6.x; let's see how it looks like (in ~10 min)

**Comment by phadej** [comment]
Ok. Same result. Locally I getÖ

![screenshot from 2018-12-21 20-08-12](https://user-images.githubusercontent.com/51087/50357042-3de49a00-055d-11e9-8ce7-042301bad490.png)

I think this should be reported to haddock https://github.com/haskell/haddock. I'm not sure what we can do. (I'd like not to upload docs manually, it's cumbersome).

**Comment by kosmikus** [comment]
@phadej But did you manually upload now? Because I see something that looks like in your last comment, not anything wrong.

Although I'm also surprised that now all the kinds are printed, and in `sop-core` they aren't. Is this a Haddock change? A GHC version change? Or can it be controlled via flags?

**Comment by kosmikus** [comment]
I'm pretty sure the Hackage docs are correct now (at least for `NS`; didn't check everything), although they're still quite different from the `sop-core` docs. I don't know very much about Haddock, and I'm not sure if it's a Haddock bug if it's "gone" with 8.6.3. But sure, we probably should ask.

**Comment by phadej** [comment]
@kosmikus are you sure you are looking in the right place, https://hackage.haskell.org/package/generics-sop-0.4.0.1/docs/Generics-SOP.html#v:Z is `Z :: NS a (x ': xs)` for me.

I'm anyway confused by

```haskell
data NS (a :: [k] -> Type) (b :: [k]) :: forall k. (k -> Type) -> [k] -> Type where
```

I can see how it's not super wrong, but it's Agda/Coq-wrong.

**Comment by RyanGlScott** [comment]
This is sad—I thought I had fixed this Haddock issue in haskell/haddock#702, but this seems to have regressed, since this issue still persists even on GHC HEAD...

**Comment by RyanGlScott** [comment]
haskell/haddock#1005 has been merged upstream, so the next version of Haddock will feature a fix for this issue.

**Comment by kosmikus** [comment]
@RyanGlScott Thanks a lot. I'll see if I can build Haddock from the repo and perhaps rebuild/reupload the documentation using that.

**Comment by kosmikus** [comment]
@RyanGlScott Thanks again. I'm getting better results now, but they're still not quite perfect.

In `sop-core`, for the original definition, the datatype is printed as
```haskell
data NP :: (k -> Type) -> [k] -> Type where
```
and the constructors as
```haskell
Nil :: NP f '[]
(:*) :: f x -> NP f xs -> NP f (x ': xs)
```

In `generics-sop`, the re-exported version is printed as
```haskell
data NP (a :: k -> Type) (b :: [k]) where
```
and the constructors as
```haskell
Nil :: forall k (a :: k -> Type) (b :: [k]). NP a ([] :: [k])
(:*) :: forall k (a :: k -> Type) (b :: [k]) (x :: k) (xs :: [k]). a x -> NP a xs -> NP a (x ': xs)
```
Do you know why the re-exported version is so completely different from the original, and whether this can somehow be avoided?

It's also quite strange that somehow `f` gets renamed to `a`. whereas `x` and `xs` "survive".

**Comment by RyanGlScott** [comment]
> Do you know why the re-exported version is so completely different from the original, and whether this can somehow be avoided?

From my (limited) understanding of how Haddock works, Haddock goes through completely different code paths depending on whether you:

1. Render things that are defined within the same package (where Haddock can just render the source code directly)
2. Render things that are imported from some external package (where Haddock must do extra work to look up the things from interface files)

The output you see for `sop-core` corresponds to code path (1), while the output you see for `generics-sop` corresponds to code path (2). I'm not aware of a way to configure Haddock to change this, although it's worth noting that one goal of the ongoing Hi Haddock project is to consolidate these code paths.

> It's also quite strange that somehow f gets renamed to a. whereas x and xs "survive".

I believe this is a consequence of code path (2). In order to render things from external packages, Haddock must infer information about that thing from the inferface file it lives in. Within an interface file, GHC serializes `NP` into a format that looks something like this:

```haskell
data NP @k (a :: k -> Type) (b :: [k])
  = (b ~ '[]) => Nil
  | forall x xs. (b ~ (x:xs)) => (:*) (a x) (NP a xs)
```

Where all universal quantification, existential quantification, and existential constraints are made explicit. Note that GHC had to invent the names `a` and `b` when writing `NP` to the interface file since you had originally wrote it as `data NP :: (k -> Type) -> [k] -> Type` (without explicitly naming those arguments). It appears that these fresh names take precedence over everything else, which is why they appear in the constructors. On the other hand, `x` and `xs` are names for existential variables (which exist on a per-constructor basis), so GHC was able to reuse those names in `(:*)`.

One way to make this slightly more tolerable is to define `NP` like this:

```diff
diff --git a/sop-core/src/Data/SOP/NP.hs b/sop-core/src/Data/SOP/NP.hs
index fbd0add..543d1a8 100644
--- a/sop-core/src/Data/SOP/NP.hs
+++ b/sop-core/src/Data/SOP/NP.hs
@@ -128,7 +128,7 @@ import Data.SOP.Sing
 -- > K 0      :* K 1     :* Nil  ::  NP (K Int) '[ Char, Bool ]
 -- > Just 'x' :* Nothing :* Nil  ::  NP Maybe   '[ Char, Bool ]
 --
-data NP :: (k -> Type) -> [k] -> Type where
+data NP (f :: k -> Type) (l :: [k]) where
   Nil  :: NP f '[]
   (:*) :: f x -> NP f xs -> NP f (x ': xs)

```

That way, GHC will reuse the name `f` when writing `NP` to an interface file, which (I believe) will convince Haddock to use the same name when rendering the constructors of `NP`.

**Comment by kosmikus** [comment]
@RyanGlScott Thanks for the thorough explanation and also the suggestion to improve the docs by changing the definition of `NP`.

For now, I've re-uploaded documentation generated with current Haddock.

Do you think that it might be an easy fix to at least drop the "redundant" quantification over `b` in the documentation of the re-exported constructors for `NP`?
```
Nil :: forall k (a :: k -> Type) (b :: [k]). NP a ([] :: [k])
(:*) :: forall k (a :: k -> Type) (b :: [k]) (x :: k) (xs :: [k]). a x -> NP a xs -> NP a (x ': xs)
```

**Comment by RyanGlScott** [comment]
Oh dear, I didn't notice that redundant quantification until you pointed it out! That looks like an entirely separate bug. Patch here: haskell/haddock#1016

**Comment by RyanGlScott** [comment]
haskell/haddock#1016 has also been merged, and should debut in the next Haddock release (likely alongside GHC 8.8).

**Comment by kosmikus** [comment]
@RyanGlScott Thanks. I'll try to rebuild and reupload documentation again once I'm back from vacation.

**Comment by kosmikus** [comment]
For 0.5, I've uploaded Haddocks using a snapshot of the ghc-8.8 branch which includes @RyanGlScott 's fixes. As far as I can see, the type signatures are now ok. Thanks for your help.
