### ISSUE TITLE
What is the purpose of the "AllF" type family in the "All" class?

### ISSUE THREAD

**Issue by danidiaz** [well-typed/generics-sop#98]
Hi, I have a question about the design of the library.

The [`All`](http://hackage.haskell.org/package/sop-core-0.4.0.0/docs/Data-SOP-Constraint.html#t:All) class is used to require a constraint for every element of a list. The constraint is required for each element `x` two times. One in this instance:

    instance (c x, All c xs) => All c (x ': xs) where
      cpara_SList p nil cons =
        cons (cpara_SList p nil cons)

And another in [`AllF`](http://hackage.haskell.org/package/sop-core-0.4.0.0/docs/Data-SOP-Constraint.html#t:AllF), a type family which creates a "list" of preconditions for `All`:

    class (AllF c xs, SListI xs) => All ...

    type family
      AllF (c :: k -> Constraint) (xs :: [k]) :: Constraint where
      AllF _c '[]       = ()
      AllF  c (x ': xs) = (c x, All c xs)

My question is, what necessitates this duplication? Especially considering that `AllF` seems to require somewhat advanced extensions like `UndecidableSuperClasses`.

**Comment by kosmikus** [comment]
Sorry for the late answer.

The short summary is that it is a trade-off, and I've been thinking about possibly removing the type family in a future version myself.

The main thing that the type family provides is that `All c xs` really means that you can assume `c x` to hold for all elements of `xs`. A contrived example:
```
f :: (All Show '[ Int, Bool ]) => (Int, Bool) -> String
f (x, y) = show x ++ show y
```
This works because of the type family. It wouldn't work if `All` is just defined as a class.

Historically, the type family was first, and everything was defined via the type family. The class was added later, primarily in order to have a good place for defining cata/paramorphisms on the type-level list structure. If one is willing to define all recursive functions on type-level lists via the cata/paramorphism, then as far as generics-sop functionality is concerned, the type family is no longer needed. It might still be "expected" by users that it has the type-family semantics though.

**Comment by phadej** [comment]
Complete example, for completeness

```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE ConstraintKinds, TypeOperators #-}
{-# LANGUAGE KindSignatures, PolyKinds, MultiParamTypeClasses #-}
{-# LANGUAGE FlexibleInstances, FlexibleContexts #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeFamilies #-}

import Data.Kind

-------------------------------------------------------------------------------
-- Class
-------------------------------------------------------------------------------

data NP f xs where
    Nil  :: NP f '[]
    (:*) :: f x -> NP f xs -> NP f (x ': xs)

infixr 5 :*

data Dict c a where
    Dict :: c a => Dict c a

class All (c :: k -> Constraint) (xs :: [k]) where
    allDicts :: NP (Dict c) xs

instance All c '[] where
    allDicts = Nil

instance (c x, All c xs) => All c (x ': xs) where
    allDicts = Dict :* allDicts

f :: forall a b. (All Show '[ a, b ]) => (a, b) -> String
f (x, y) = case allDicts :: NP (Dict Show) '[ a, b ] of
    Dict :* Dict :* Nil -> show x ++ show y

-------------------------------------------------------------------------------
-- Family
-------------------------------------------------------------------------------

type family AllF (c :: k -> Constraint) (xs :: [k]) :: Constraint where
    AllF c '[]       = ()
    AllF c (x ': xs) = (c x, AllF c xs)

g :: forall a b. (AllF Show '[ a, b ]) => (a, b) -> String
g (x, y) = show x ++ show y
```

**Comment by kosmikus** [comment]
Going to close this for now. I think I'll keep the current behaviour at least until a point when I finally feel confident to switch to one of the "static case" branches.
